### ISSUE TITLE
Can't add PTR or HOST records

### ISSUE THREAD

**Issue by st33v** [prudhvitella/terraform-provider-infoblox#16]
I'd like to add reverse DNS addresses for my A records.

The provider does not allow PTR records, nor does it allow HOST records which appears to be an infoblox-specific thing that will create the A record AND the PTR for reverse lookups.

**Comment by JackBracken** [comment]
I'm going to take a crack at this. Looking at the infoblox WAPI, I think it makes a lot more sense to break record types out into their own resources, ie `infoblox_record_a`, `infoblox_record_cname`, `infoblox_record_ptr`, `infoblox_record_host` etc. Obviously this would be a breaking change so I'll have to be careful about how I organise it.

**Comment by JackBracken** [comment]
Need to write tests and stuff but have something basic working.

[Example HCL syntax for PTR](https://github.com/prudhvitella/terraform-provider-infoblox/commit/38a29ccd4ad33ab0e53452f959eb996771d9e067?diff=split#diff-04c6e90faac2675aa89e2176d2eec7d8R122) and the [code itself](https://github.com/prudhvitella/terraform-provider-infoblox/commit/38a29ccd4ad33ab0e53452f959eb996771d9e067?diff=split#diff-5afac574c05a5ac752bc83e484e45100) type. Lots of work needed for the HOST record but hopefully I'll get it done soon.

**Comment by JackBracken** [comment]
Not merged yet, but: https://github.com/prudhvitella/terraform-provider-infoblox/pull/27
