### ISSUE TITLE
Error type assertion panic

### ISSUE THREAD

**Issue by SJChacko** [prudhvitella/terraform-provider-infoblox#23]
Hi, we are getting occasional 'panic: interface conversion: error is *errors.errorString, not infoblox.Error' which come from the type assertion err.(infoblox.Error).Code() in the handleReadError function in resource_infoblox_record.go

It seems to be trying to assert that an ordinary go error (from fmt.Errorf in this case) is an infoblox.Error

It would be possible to check for this using the type assertion test  (t, ok := i.(T)) which should stop the panic. But would that be just covering up a problem elsewhere?

thanks, Sarah

**Comment by wtsi-mercury** [comment]
Oops - this was an oversight on my part in the `handleReadError` implementation - didn't catch that it can receive errors that are not of type `infoblox.Error`. @SJChacko's suggested fix (type assertion check wrapping that code) looks like it should work.

**Comment by jrandall** [comment]
Oops - this was an oversight on my part in the `handleReadError` implementation - didn't catch that it can receive errors that are not of type `infoblox.Error`. @SJChacko's suggested fix (type assertion check wrapping that code) looks like it should work.
