### ISSUE TITLE
Unable to update A records

### ISSUE THREAD

**Issue by lex00** [prudhvitella/terraform-provider-infoblox#33]
Hello, when I attempt to update an A record, I get the following response.  I built the provider with the latest source.  Thanks for any help.

```
* infoblox_record_a.dev-cf41-test2-kafka1: error updating Infoblox A record: Error AdmConProtoError: Field is not allowed for update: view - Client.Ibap.Proto - Field is not allowed for update: view
```

**Comment by zoobab** [comment]
I have the same error.

When the A record is first created, it goes fine, but when I rerun terraform, it fails.

I have to comment out line starting with "view" to get it passed.

Is there some logic to fix here?

**Comment by JackBracken** [comment]
Should be fixed in the latest release.
