### ISSUE TITLE
TTL and comments do not get set on A records

### ISSUE THREAD

**Issue by lex00** [prudhvitella/terraform-provider-infoblox#34]
When I setup a new A record, the provider wants to set the comment and TTL again on the next apply.  A second apply does not set the values.

My workaround for now is to not set TTL or comment.  The comment is off less concern.

**Comment by JackBracken** [comment]
Hi @lex00, thanks for opening the issue. My off-hand suspicion is that something in the `populateSharedAttributes` function isn't behaving the way I'd expect, but I'm unusually busy just at the moment. I'd like to dive deeper on this and #33 but it may take me a few days. Thanks again!

**Comment by JackBracken** [comment]
This should now be fixed for A records in the latest release. I'll roll out and test the changes for other records soon too. Thanks!
