### ISSUE TITLE
need suggestion.

### ISSUE THREAD

**Issue by ghost** [prudhvitella/terraform-provider-infoblox#47]
Is there anyway we can download provider using provider_url instead of manually downloading and copying to plugin directory.
 provider "infoblox" {
  provider_url = "https://github.com/prudhvitella/terraform-provider-infoblox/releases/download/pre-release/darwin_386_terraform-provider-infoblox"

}

**Comment by JackBracken** [comment]
Hi @gvelu , I'm not aware of any provider_url configuration option for terraform providers, nor can I find one documented anywhere. Unfortunately there's no way to have terraform automatically install a 3rd party provider that I'm aware of. I'm going to close this issue but feel free to reopen if I've misunderstood.
