### ISSUE TITLE
invalid remote plugin...

### ISSUE THREAD

**Issue by st33v** [prudhvitella/terraform-provider-infoblox#8]
Using both terraform 0.8.4 and 0.8.6 gives me:
> Error configuring: 1 error(s) occurred:
> 
> * Unrecognized remote plugin message: 2|unix|/var/folders/9k/gqp_92xx5ml9__33gkmw7wrj69yys9/T/tf-plugin282817430
> 
> This usually means that the plugin is either invalid or simply
needs to be recompiled to support the latest protocol.`

**Comment by st33v** [comment]
I tried to recompile but the most I could get it to do was segfault.

**Comment by JackBracken** [comment]
Hi @st33v I had a similar issue but resolved it by doing the following:

Clone the project:

```
git clone git@github.com:prudhvitella/terraform-provider-infoblox.git $GOPATH/src/github.com/prudhvitella/terraform-provider-infoblox
```

Fetch the dependencies:

```
cd $GOPATH/src/github.com/prudhvitella/terraform-provider-infoblox
go get ./...
```

Checkout the terraform version tag you want to build against:

```
cd $GOPATH/src/github.com/hashicorp/terraform
git fetch --all --tags --prune
git checkout tags/v0.8.6
```

Rebuild the plugin:

```
cd -
bash scripts/build.sh
```

Hope this is helpful.

**Comment by prudhvitella** [comment]
I updated vendor.json to v0.8.8. The plugin should work with v0.8.8 now.

**Comment by st33v** [comment]
Thanks!
